// Custom Supabase client pointing to the user-managed project (xqvksijbumgeaggcucmh).
// Do NOT use src/integrations/supabase/client.ts — that file is auto-regenerated by Lovable
// and points to the Lovable Cloud project. Always import from "@/lib/supabase-client".
import { createClient } from "@supabase/supabase-js";
import type { Database } from "@/integrations/supabase/types";

const SUPABASE_URL = "https://xqvksijbumgeaggcucmh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_cGsQ4yXkj-Ws56hZVoMq2A_IswAYTxk";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});

export const SUPABASE_PROJECT_URL = SUPABASE_URL;
