project_id = "mpemgdvmvilqbzmbiwpg"

[functions.stripe-subscription-webhook]
verify_jwt = false

[functions.stripe-order-webhook]
verify_jwt = false

[functions.create-order-checkout]
verify_jwt = false
